export const forms = [
  {
    id: 1,
    title: "Titre du formulaire lorem ipsum dolor sit",
    category: "Catégorie bien1",
    author: "André Monroe",
    publishDate: "Publié le 08 Juin 2026 à 16:36",
    expiryDate: "Expire le 19 Juillet 2026 à 16:36",
    responses: 0,
    isFavorite: false,
  },
  {
    id: 2,
    title: "Formulaire de contact client",
    category: "Catégorie bien2",
    author: "Marie Dubois",
    publishDate: "Publié le 15 Mai 2026 à 14:20",
    expiryDate: "Expire le 20 Août 2026 à 14:20",
    responses: 5,
    isFavorite: true,
  },
  {
    id: 3,
    title: "Enquête de satisfaction",
    category: "Catégorie bien1",
    author: "Pierre Martin",
    publishDate: "Publié le 22 Avril 2026 à 10:15",
    expiryDate: "Expire le 30 Juin 2026 à 10:15",
    responses: 12,
    isFavorite: false,
  },
  {
    id: 4,
    title: "Formulaire d'inscription événement",
    category: "Catégorie bien3",
    author: "André Monroe",
    publishDate: "Publié le 03 Juillet 2026 à 09:30",
    expiryDate: "Expire le 15 Septembre 2026 à 09:30",
    responses: 8,
    isFavorite: false,
  },
  {
    id: 5,
    title: "Demande de devis",
    category: "Catégorie bien2",
    author: "Sophie Laurent",
    publishDate: "Publié le 12 Mars 2026 à 11:45",
    expiryDate: "Expire le 25 Mai 2026 à 11:45",
    responses: 3,
    isFavorite: true,
  },
  {
    id: 6,
    title: "Feedback produit",
    category: "Catégorie bien1",
    author: "Marie Dubois",
    publishDate: "Publié le 28 Février 2026 à 16:00",
    expiryDate: "Expire le 10 Avril 2026 à 16:00",
    responses: 15,
    isFavorite: false,
  },
  {
    id: 7,
    title: "Formulaire de candidature",
    category: "Catégorie bien3",
    author: "Pierre Martin",
    publishDate: "Publié le 18 Janvier 2026 à 13:25",
    expiryDate: "Expire le 28 Mars 2026 à 13:25",
    responses: 22,
    isFavorite: true,
  },
  {
    id: 8,
    title: "Évaluation de formation",
    category: "Catégorie bien2",
    author: "André Monroe",
    publishDate: "Publié le 05 Décembre 2025 à 08:50",
    expiryDate: "Expire le 15 Février 2026 à 08:50",
    responses: 7,
    isFavorite: false,
  },
  {
    id: 9,
    title: "Questionnaire de recherche",
    category: "Catégorie bien1",
    author: "Sophie Laurent",
    publishDate: "Publié le 14 Novembre 2025 à 15:10",
    expiryDate: "Expire le 20 Janvier 2026 à 15:10",
    responses: 18,
    isFavorite: false,
  },
];
